### ISSUE TITLE
ownCloud 10.13.0 incompatible with sciencemesh

### ISSUE THREAD

**Issue by MahdiBaghbani** [sciencemesh/nc-sciencemesh#38]
Installing Sciencemesh in ownCloud 10.13.0 causes this:
```json
{
  "reqId": "QiKZk37MPSuV4fI6h7Us",
  "level": 4,
  "time": "2023-08-24T07:39:40+00:00",
  "remoteAddr": "172.18.0.3",
  "user": "einstein",
  "app": "webdav",
  "method": "PROPFIND",
  "url": "/remote.php/dav/files/einstein/",
  "message": "Exception: No share provider for share type 7: {\"Exception\":\"OC\\\\Share20\\\\Exception\\\\ProviderException\",\"Message\":\"No share provider for share type 7\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/html\\/lib\\/private\\/Share20\\/Manager.php(160): OCA\\\\ScienceMesh\\\\ScienceMeshProviderFactory->getProviderForType()\\n#1 \\/var\\/www\\/html\\/lib\\/private\\/Share20\\/Manager.php(1272): OC\\\\Share20\\\\Manager->shareTypeToProviderMap()\\n#2 \\/var\\/www\\/html\\/apps\\/dav\\/lib\\/Connector\\/Sabre\\/SharesPlugin.php(146): OC\\\\Share20\\\\Manager->getAllSharesBy()\\n#3 \\/var\\/www\\/html\\/apps\\/dav\\/lib\\/Connector\\/Sabre\\/SharesPlugin.php(197): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\SharesPlugin->getSharesForNodeIds()\\n#4 \\/var\\/www\\/html\\/lib\\/composer\\/sabre\\/event\\/lib\\/WildcardEmitterTrait.php(89): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\SharesPlugin->handleGetProperties()\\n#5 \\/var\\/www\\/html\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(1052): Sabre\\\\DAV\\\\Server->emit()\\n#6 \\/var\\/www\\/html\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(984): Sabre\\\\DAV\\\\Server->getPropertiesByNode()\\n#7 \\/var\\/www\\/html\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(1662): Sabre\\\\DAV\\\\Server->getPropertiesIteratorForPath()\\n#8 \\/var\\/www\\/html\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(1642): Sabre\\\\DAV\\\\Server->writeMultiStatus()\\n#9 \\/var\\/www\\/html\\/lib\\/composer\\/sabre\\/http\\/lib\\/Sapi.php(83): Sabre\\\\DAV\\\\Server->Sabre\\\\DAV\\\\{closure}(*** sensitive parameters replaced ***)\\n#10 \\/var\\/www\\/html\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(490): Sabre\\\\HTTP\\\\Sapi::sendResponse()\\n#11 \\/var\\/www\\/html\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod()\\n#12 \\/var\\/www\\/html\\/apps\\/dav\\/lib\\/Server.php(348): Sabre\\\\DAV\\\\Server->start()\\n#13 \\/var\\/www\\/html\\/apps\\/dav\\/appinfo\\/v2\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#14 \\/var\\/www\\/html\\/remote.php(165): require_once('\\/var\\/www\\/html\\/a...')\\n#15 {main}\",\"File\":\"\\/var\\/www\\/html\\/apps\\/sciencemesh\\/lib\\/ScienceMeshProviderFactory.php\",\"Line\":137}"
}
```

Share type 7 is the problem that didn't exist in ownCloud 10.12.2

**Comment by MahdiBaghbani** [comment]
The share type has been introduced by RD-SRAM project, merged into ownCloud core by this PR https://github.com/owncloud/core/pull/40886

Share typ 7 is the `\OCP\Share::SHARE_TYPE_REMOTE_GROUP`, which needs to be handled on the Sciencemesh app.
